### ISSUE TITLE
Accept `stdin` as input 

### ISSUE THREAD

**Issue by polyrain** [ttytm/nimpretty_t#1]
This is a great project! I've been using it while writing Nim lately, but I'd like to use it within Helix as my default formatter. Unfortunately, Helix needs the formatter to be able to accept the original program as input over `stdin`, and emit it via `stdout` (which `nimpretty_t` already does).

Is this something that would be able to be looked at?

**Comment by ttytm** [comment]
Hello @polyrain,

Glad to hear it's already helping. I see the problem and gonna look into it. However, the earliest I can make time is next week, please bear with me. And thanks for the report 🙂

**Comment by ttytm** [comment]
@polyrain the latest release should allow you to format input from std. Let me if things work for you 🙂
